### ISSUE TITLE
`<Plug>QlistInclude*` runs into: No matching autocommands

### ISSUE THREAD

**Issue by shmup** [romainl/vim-qlist#14]
1) Could easily be something interfering, because I haven't properly debugged. All I know is if I remove vim-qlist, then `[I`, it outputs correctly

2) vim 8.2, recently compiled from HEAD

3) If there's anything I can do to unveil this more, just ask it of me :) I've been wanting to get around to it. I really love `[I`, it's such fantastic insight

**Comment by romainl** [comment]
Hmm… I couldn't reproduce this on 8.2.2576.

**Comment by shmup** [comment]
I definitely, without a doubt, and gonna return to debugging this shortly. Sadly my stack was still doing it when I limited it to just this plugin, oh no haha

I'll go about thinking about my various scripts, vim build, etc, in time.. 

edit: ok, in hindsight, I specifically remember removing all other plugins except both your vim-qf and vim-qlist. What a terrible way to test, given my comment below, ha

**Comment by shmup** [comment]
Interesting.. I narrowed it down to a single plugin: `vim-qf`.

This commit in particular: https://github.com/romainl/vim-qf/commit/28f7f73a328a0699ebe33a336dce8060e38fff78

Noting this now in case I don't get back to debugging

**Comment by romainl** [comment]
The culprit is most likely this line: https://github.com/romainl/vim-qlist/blob/master/autoload/qlist.vim#L72. `:cwindow` is not a "quickfix command" for `QuickFixCmdPost`.

I will try to fix it this week-end. Feel free to open a PR if you manage to do it before me.

(I couldn't reproduce the issue because the vim-qlist in my config is not up to date, sorry.)
